/** Unique image paths — one asset per marketing slot (no reuse). */
export const mktImg = {
  homeHero: "/marketing/hero-home.jpg",
  homeFree: "/marketing/band-free.jpg",
  homeAudience: "/marketing/split-audience-home.jpg",
  homeBreak1: "/marketing/home-break-1.jpg",
  homeBreak2: "/marketing/home-break-2.jpg",
  homeBreak3: "/marketing/home-break-3.jpg",
  homeMove1: "/marketing/home-move-1.jpg",
  homeMove2: "/marketing/home-move-2.jpg",
  homeMove3: "/marketing/home-move-3.jpg",

  aboutHero: "/marketing/hero-about.jpg",
  aboutFocus: "/marketing/about-focus.jpg",
  aboutP1: "/marketing/about-p1.jpg",
  aboutP2: "/marketing/about-p2.jpg",
  aboutP3: "/marketing/about-p3.jpg",
  aboutP4: "/marketing/about-p4.jpg",

  servicesHero: "/marketing/hero-services.jpg",
  servicesAudience: "/marketing/svc-audience.jpg",
  svcClients: "/marketing/svc-clients.jpg",
  svcQuotes: "/marketing/svc-quotes.jpg",
  svcConvert: "/marketing/svc-convert.jpg",
  svcQr: "/marketing/svc-qr.jpg",
  svcConfirm: "/marketing/svc-confirm.jpg",
  svcRemind: "/marketing/svc-remind.jpg",
  svcBoard: "/marketing/svc-board.jpg",

  blogHero: "/marketing/hero-blog.jpg",
  contactHero: "/marketing/hero-contact.jpg",
  contactDock: "/marketing/dock-contact.jpg",
  contactFit: "/marketing/contact-fit.jpg",
  contactOps: "/marketing/contact-ops.jpg",
  contactAccount: "/marketing/contact-account.jpg",
  privacyHero: "/marketing/hero-privacy.jpg",
  termsHero: "/marketing/hero-terms.jpg",
  enterBg: "/marketing/bg-enter.jpg",
  electricDeep: "/marketing/electric-deep.jpg",
  electricMid: "/marketing/electric-mid.jpg",
  electricPanel: "/marketing/electric-panel.jpg",
  electricTeal: "/marketing/electric-teal.jpg",

  /** Unique SEO marketing pages (generated — do not reuse elsewhere) */
  seoPricingHero: "/marketing/seo-pricing-hero.png",
  seoPricingIncluded: "/marketing/seo-pricing-included.png",
  seoPricingLimits: "/marketing/seo-pricing-limits.png",
  seoPricingNotGst: "/marketing/seo-pricing-not-gst.png",
  seoFaqHero: "/marketing/seo-faq-hero.png",
  seoFaqCards: "/marketing/seo-faq-cards.png",
  seoUpiHero: "/marketing/seo-upi-hero.png",
  seoUpiScan: "/marketing/seo-upi-scan.png",
  seoUpiConfirm: "/marketing/seo-upi-confirm.png",
  seoFreelancerHero: "/marketing/seo-freelancer-hero.png",
  seoFreelancerDesk: "/marketing/seo-freelancer-desk.png",
  seoClinicHero: "/marketing/seo-clinic-hero.png",
  seoClinicRoom: "/marketing/seo-clinic-room.png",
  seoContractorHero: "/marketing/seo-contractor-hero.png",
  seoContractorBoard: "/marketing/seo-contractor-board.png",
  seoCompareExcelHero: "/marketing/seo-compare-excel-hero.png",
  seoCompareExcelChaos: "/marketing/seo-compare-excel-chaos.png",
  seoCompareZohoHero: "/marketing/seo-compare-zoho-hero.png",
  seoCompareZohoLean: "/marketing/seo-compare-zoho-lean.png",
  seoStoryHero: "/marketing/seo-story-hero.png",
  seoStoryConfirm: "/marketing/seo-story-confirm.png",

  seoCardZohoBreadth: "/marketing/seo-card-zoho-breadth.png",
  seoCardFolioLean: "/marketing/seo-card-folio-lean.png",
  seoCardGstHonesty: "/marketing/seo-card-gst-honesty.png",
  seoCardCostFree: "/marketing/seo-card-cost-free.png",
  seoCardFaqFree: "/marketing/seo-card-faq-free.png",
  seoCardFaqGateway: "/marketing/seo-card-faq-gateway.png",
  seoCardFaqNotGst: "/marketing/seo-card-faq-not-gst.png",
  seoCardFaqQr: "/marketing/seo-card-faq-qr.png",
  seoCardFaqNoSignup: "/marketing/seo-card-faq-no-signup.png",
  seoCardFaqClaim: "/marketing/seo-card-faq-claim.png",
  seoCardFaqWhatsapp: "/marketing/seo-card-faq-whatsapp.png",
  seoCardFaqLocation: "/marketing/seo-card-faq-location.png",
  seoCardFaqConvert: "/marketing/seo-card-faq-convert.png",
  seoCardFaqAudience: "/marketing/seo-card-faq-audience.png",
  seoCardUpiRails: "/marketing/seo-card-upi-rails.png",
  seoCardUpiQr: "/marketing/seo-card-upi-qr.png",
  seoCardUpiClaim: "/marketing/seo-card-upi-claim.png",
  seoCardUpiGuest: "/marketing/seo-card-upi-guest.png",
  seoCardFlFree: "/marketing/seo-card-fl-free.png",
  seoCardFlLinks: "/marketing/seo-card-fl-links.png",
  seoCardFlClaim: "/marketing/seo-card-fl-claim.png",
  seoCardFlCa: "/marketing/seo-card-fl-ca.png",
} as const;
