/** Unique image paths — one asset per marketing slot (no reuse). */
export const mktImg = {
  homeHero: "/marketing/hero-home.jpg",
  homeFree: "/marketing/band-free.jpg",
  homeAudience: "/marketing/split-audience-home.jpg",
  homeBreak1: "/marketing/home-break-1.jpg",
  homeBreak2: "/marketing/home-break-2.jpg",
  homeBreak3: "/marketing/home-break-3.jpg",
  homeMove1: "/marketing/home-move-1.jpg",
  homeMove2: "/marketing/home-move-2.jpg",
  homeMove3: "/marketing/home-move-3.jpg",

  aboutHero: "/marketing/hero-about.jpg",
  aboutFocus: "/marketing/about-focus.jpg",
  aboutP1: "/marketing/about-p1.jpg",
  aboutP2: "/marketing/about-p2.jpg",
  aboutP3: "/marketing/about-p3.jpg",
  aboutP4: "/marketing/about-p4.jpg",

  servicesHero: "/marketing/hero-services.jpg",
  servicesAudience: "/marketing/svc-audience.jpg",
  svcClients: "/marketing/svc-clients.jpg",
  svcQuotes: "/marketing/svc-quotes.jpg",
  svcConvert: "/marketing/svc-convert.jpg",
  svcQr: "/marketing/svc-qr.jpg",
  svcConfirm: "/marketing/svc-confirm.jpg",
  svcRemind: "/marketing/svc-remind.jpg",
  svcBoard: "/marketing/svc-board.jpg",

  blogHero: "/marketing/hero-blog.jpg",
  contactHero: "/marketing/hero-contact.jpg",
  contactDock: "/marketing/dock-contact.jpg",
  contactFit: "/marketing/contact-fit.jpg",
  contactOps: "/marketing/contact-ops.jpg",
  contactAccount: "/marketing/contact-account.jpg",
  privacyHero: "/marketing/hero-privacy.jpg",
  termsHero: "/marketing/hero-terms.jpg",
  enterBg: "/marketing/bg-enter.jpg",
  electricDeep: "/marketing/electric-deep.jpg",
  electricMid: "/marketing/electric-mid.jpg",
  electricPanel: "/marketing/electric-panel.jpg",
  electricTeal: "/marketing/electric-teal.jpg",
} as const;
